List *Create(void);
whatever ***Insert(List *list, int data);
int Size(List *list);
int *IsEmpty(List *list);
int GetFirst(List *list);
int main();
List *Create(void);
whatever ***Insert(List *list, int data);
int Size(List *list);
int *IsEmpty(List *list);
int GetFirst(List *list);
int main();
